#:schema node_modules/wrangler/config-schema.json
name = "meal-prep-api"
main = "src/main.py"
compatibility_date = "2026-04-25"
compatibility_flags = ["python_workers", "disable_python_external_sdk"]


[[d1_databases]]
binding = "meal_prep_db"
database_name = "meal_prep_db"
database_id = "d99d6b0b-7fb2-4443-8068-80e687c97d00"
